# -*- coding: utf-8 -*-
"""Projeto IA Agentes - Plataforma de verificação de notícias.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17B9FLVYcFFHiBscq7-RtISQYZLnMmuJO
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip -q install google-genai

# Configura a API Key do Google Gemini

import os
from google.colab import userdata

os.environ["GOOGLE_API_KEY"] = userdata.get('GOOGLE_API_KEY')

# Configura o cliente da SDK do Gemini

from google import genai

client = genai.Client()

MODEL_ID = "gemini-2.0-flash"

from IPython.display import HTML, Markdown

# Instalar Framework ADK de agentes do Google ################################################

!pip -q install google-adk

from google.adk.agents import Agent ## base de agentes
from google.adk.runners import Runner #osquestrador entre agentes
from google.adk.sessions import InMemorySessionService ##memória interna do osquestrador
from google.adk.tools import google_search # tool
from google.genai import types  # Para criar conteúdos (Content e Part)
from datetime import date
import textwrap # Para formatar melhor a saída de texto
from IPython.display import display, Markdown # Para exibir texto formatado no Colab
import requests # Para fazer requisições HTTP
import warnings

warnings.filterwarnings("ignore")

# Função auxiliar que envia uma mensagem para um agente via Runner e retorna a resposta final
def call_agent(agent: Agent, message_text: str) -> str:
    # Cria um serviço de sessão em memória
    session_service = InMemorySessionService()
    # Cria uma nova sessão (você pode personalizar os IDs conforme necessário)
    session = session_service.create_session(app_name=agent.name, user_id="user1", session_id="session1")
    # Cria um Runner para o agente
    runner = Runner(agent=agent, app_name=agent.name, session_service=session_service)
    # Cria o conteúdo da mensagem de entrada
    content = types.Content(role="user", parts=[types.Part(text=message_text)])

    final_response = ""
    # Itera assincronamente pelos eventos retornados durante a execução do agente
    for event in runner.run(user_id="user1", session_id="session1", new_message=content):
        if event.is_final_response():
          for part in event.content.parts:
            if part.text is not None:
              final_response += part.text
              final_response += "\n"
    return final_response

# Função auxiliar para exibir texto formatado em Markdown no Colab
def to_markdown(text):
  text = text.replace('•', '  *')
  return Markdown(textwrap.indent(text, '> ', predicate=lambda _: True))

##########################################
# --- Agente 1: Buscador de Notícias reais --- #
##########################################

def agente_buscador1(topico, data_de_hoje):
  buscador1 = Agent(
      name="agente_buscador1",
      model="gemini-2.0-flash",
      description="Agente que busca notícias sobre o tópico indicado",#preciso indicar o nome e modelo dele"
      tools=[google_search],
      instruction="""
      Você é um assistente de pesquisa. A sua tarefa é usar a ferramenta de busca do google (google_search)
      Para recuperar as ultimas notícias muito relevantes sobre o tópico abaixo.
      Foque em no máximo 3 notícias relevantes de cada item, com base na quantidade e entusiasmo das notícias sobre ele.
      Além disso, sempre priorize trazer dados técnicos e números sobre cada item.
      Item 1: Você deve priorizar a informação de notícias reais, confirme sempre se os sites apresentados são de fontes confiáveis.
      Item 2: Você deve priorizar o levantamento de notícias falsas sobre o tópico, para que seja validado pelo verificador de notícias.
      """

  )
  entrada_do_agente_buscador1 = f"Tópico: {topico}\nData de hoje: {data_de_hoje}" #Adiciono as duas entradas da funçao criada acima
  # Executa o agente
  lancamento1 = call_agent(buscador1, entrada_do_agente_buscador1) #chamo agente para executação da função acima com as entradas
  return lancamento1

################################################
# --- Agente 2: Verificador de notícias --- #
################################################
def agente_verificador(topico, lancamentos_buscados):
    verificador = Agent(
        name="agente_verificador",
        model="gemini-2.0-flash",
        # Inserir as instruções do Agente Planejador #################################################
        instruction="""
        Você é um verificador de conteúdo, especialista em análise de notícias reais e falsa.
        Com base na listas de informações levantadas pelos buscadores, você deve:
        usar a ferramenta de busca do Google (google_search) para verificar e validar de fato quais são as notíficas reais e falsas que foram apresentadas.
        Você também pode usar o (google_search) para encontrar mais informações sobre os temas e aprofundar.
        Ao final, você irá elaborar um texto explicando a notícia real e que informação falsa está sendo associada a essa notícia.
        """,
        description="Agente que verifica notícias", #vai organizar as ideias do buscador",
        tools=[google_search]
    )

    entrada_do_agente_verificador = f"Tópico:{topico}\nLançamentos buscados: {lancamentos_buscados}"
    # Executa o agente
    verificador = call_agent(verificador, entrada_do_agente_verificador)
    return verificador

######################################
# --- Agente 3: Roteirista da informações --- #
######################################
def agente_redator(topico, plano_de_post):
    redator = Agent(
        name="agente_redator",
        model="gemini-2.0-flash",
        instruction="""
            Você é um Redator jornalístico de um dos principais jornais do país.
            Você escreve de maneira formal mas acessível para o público médio.
            Utilize o tema fornecido e os pontos mais relevantes fornecidos e, com base nisso,
            escreva um roteiro para o âncora do seu jornal apresentar ao vivo.
            A mensagem deve ser engajadora e informativa, que não passe de 30 segundos de apresentação.
            """,
        description="Agente redator de jornal"
    )
    entrada_do_agente_redator = f"Tópico: {topico}\nPlano de post: {plano_de_post}"
    # Executa o agente
    rascunho = call_agent(redator, entrada_do_agente_redator)
    return rascunho

##########################################
# --- Agente 4: Apresentador --- #
##########################################
def agente_revisor(topico, rascunho_gerado):
    apresentador = Agent(
        name="agente_apresentador",
        model="gemini-2.0-flash",
        instruction="""
            Você é o maior apresentador jornalístico do principal jornal do seu país.
            Crie um nome adequado para você e se apresente no início do jornal com nome e sobrenome.
            Por ter um público diversificado, use um tom de apresentação adequado e geral.
            Revise o roteiro indicado, verificando clareza, concisão, correção e tom.
            Se o roteiro estiver bom, apresente-o.
            Caso haja problemas, apresente-o com melhorias.
            """,
        description="Agente apresentador de jornal."

    )
    entrada_do_agente_apresentador = f"Tópico: {topico}\nRascunho: {rascunho_gerado}"
    # Executa o agente
    texto_revisado = call_agent(apresentador, entrada_do_agente_apresentador)
    return texto_revisado

data_de_hoje = date.today().strftime("%d/%m/%Y")

print("🚀 Verificação de notícias. 🚀")

# --- Obter o Tópico do Usuário ---
topico = input("❓ Por favor, digite o TÓPICO sobre o qual você quer checar um fato: ")

# Inserir lógica do sistema de agentes ################################################

if not topico:
    print("Você esqueceu de digitar o tópico!")
else:
    print(f"Ótimo! Vamos então verificar notícias sobre {topico}")

    lancamento1 = agente_buscador1(topico, data_de_hoje)
    print("\n -- Resultado do agente 1 (Buscador) -- \n")
    display(to_markdown(lancamento1))
    print("--------------------------------------------")

    verificador = agente_verificador(topico, lancamento1)
    print("\n -- Resultado do agente 2 (Verificador) -- \n")
    display(to_markdown(verificador))
    print("--------------------------------------------")

    rascunho_gerado = agente_redator(topico, verificador)
    print("\n -- Resultado do agente 3 (Redator) -- \n")
    display(to_markdown(rascunho_gerado))
    print("--------------------------------------------")

    texto_revisado = agente_revisor(topico, rascunho_gerado)
    print("\n -- Resultado do agente 4 (Apresentador) -- \n")
    display(to_markdown(texto_revisado))


## Ideia: Agente analisador de fake news que te apresenta a notícia real e
## a fake gerada recentemente